# Generated by Django 6.0.6 on 2026-07-17 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_channel_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='api.channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_access_roles', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='api.group')),
            ],
            options={
                'db_table': 'access_roles',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='custom_roles',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to='api.accessrole'),
        ),
        migrations.AddConstraint(
            model_name='accessrole',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('channel__isnull', True)), models.Q(('group__isnull', True), ('channel__isnull', False)), _connector='OR'), name='access_role_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='accessrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('group__isnull', False)), fields=('group', 'name'), name='unique_active_group_role_name'),
        ),
        migrations.AddConstraint(
            model_name='accessrole',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False), ('deleted_at__isnull', True)), fields=('channel', 'name'), name='unique_active_channel_role_name'),
        ),
    ]
