# Generated by Django 6.0.6 on 2026-07-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_channel_owner_memberships(
    apps,
    schema_editor,
):
    Channel = apps.get_model(
        "api",
        "Channel",
    )
    ChannelMembership = apps.get_model(
        "api",
        "ChannelMembership",
    )

    database_alias = schema_editor.connection.alias

    channels = Channel.objects.using(
        database_alias
    ).all()

    for channel in channels.iterator():
        ChannelMembership.objects.using(
            database_alias
        ).get_or_create(
            channel_id=channel.pk,
            user_id=channel.creator_id,
            defaults={
                "role": "owner",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_accessrole_groupmembership_custom_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.channel')),
                ('custom_roles', models.ManyToManyField(blank=True, related_name='channel_memberships', to='api.accessrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_memberships',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_channels', through='api.ChannelMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'role'], name='channel_mem_channel_86c79f_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelmembership',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='unique_channel_membership'),
        ),
        migrations.RunPython(
            create_channel_owner_memberships,
            migrations.RunPython.noop,
        ),
    ]
