# Generated by Django 6.0.6 on 2026-07-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_channelmembership_channel_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('message_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('channel', 'Channel')], default='channel', max_length=16)),
                ('group_id', models.CharField(blank=True, default='', max_length=32)),
                ('channel_id', models.CharField(blank=True, default='', max_length=32)),
                ('topic_id', models.CharField(blank=True, default='', max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(blank=True, default='')),
                ('media', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_replies', to='api.message')),
                ('sent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_origin', to='api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_messages',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
