# Generated by Django 6.0.6 on 2026-07-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scheduledmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_add_permission', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=16)),
                ('allow_direct_add', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_privacy_settings',
            },
        ),
    ]
