# Generated by Django 6.0.6 on 2026-07-29 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sticker_stickerpack_messagereaction_sticker_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('file_key', models.CharField(max_length=500, unique=True)),
                ('file_url', models.URLField(max_length=1000)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_attachments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='media_attac_owner_i_c948d7_idx'), models.Index(fields=['message', 'media_type'], name='media_attac_message_386d22_idx')],
            },
        ),
    ]
