# Generated by Django 6.0.6 on 2026-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mediaattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
