# Generated by Django 6.0.6 on 2026-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_group_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
