# Generated by Django 6.0.6 on 2026-08-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_channel_is_private_invitelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='user_contac_owner_i_727207_idx'), models.Index(fields=['owner', 'contact'], name='user_contac_owner_i_ee44c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'contact'), name='unique_user_contact'), models.CheckConstraint(condition=models.Q(('owner', models.F('contact')), _negated=True), name='user_cannot_be_own_contact')],
            },
        ),
    ]
